version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    versioning-strategy: "pin"
    open-pull-requests-limit: 1
    groups:
      ci-dependencies:
        patterns:
          - "*"
