name: Run pytest

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Follow the min version in pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest coverage
          pip install -e .

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          coverage run -m pytest && coverage xml && coverage html

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true

      - name: HTML coverage to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: coverage_html
          path: ./htmlcov
          if-no-files-found: error
